/**
 * Codex Config Writer
 *
 * Exports LegnaCode settings to Codex `config.toml` format.
 * Enables bidirectional config compatibility — users can switch
 * between the two tools without losing their configuration.
 */

import { homedir } from "os"
import { join } from "path"
import { mkdir, writeFile } from "fs/promises"
import { logForDebugging } from "../debug.js"
import type { CodexConfig } from "./codexConfigReader.js"

// ---------------------------------------------------------------------------
// Mapping: LegnaCode → Codex
// ---------------------------------------------------------------------------

/**
 * Convert LegnaCode settings (env vars + mcpServers) into a Codex config
 * object suitable for serialisation to TOML.
 */
export function mapLegnaToCodexConfig(settings: {
  env?: Record<string, string>
  mcpServers?: Record<string, unknown>
}): CodexConfig {
  const config: CodexConfig = {}

  const env = settings.env ?? {}

  // Model
  if (env.ANTHROPIC_MODEL) {
    config.model = env.ANTHROPIC_MODEL
  }

  // Sandbox mode
  if (env.CLAUDE_CODE_SANDBOX_MODE) {
    config.sandbox_mode = env.CLAUDE_CODE_SANDBOX_MODE
  }

  // Network proxy
  if (env.HTTPS_PROXY) {
    config.network_proxy = env.HTTPS_PROXY
  }

  // MCP servers
  if (settings.mcpServers && Object.keys(settings.mcpServers).length > 0) {
    config.mcp_servers = {}
    for (const [name, srv] of Object.entries(settings.mcpServers)) {
      const s = srv as Record<string, unknown>
      if (s.url) {
        config.mcp_servers[name] = {
          type: (s.type as "sse" | "http") ?? "sse",
          url: s.url as string,
        }
      } else if (s.command) {
        config.mcp_servers[name] = {
          type: "stdio",
          command: s.command as string,
          args: s.args as string[] | undefined,
          env: s.env as Record<string, string> | undefined,
        }
      }
    }
  }

  return config
}

// ---------------------------------------------------------------------------
// TOML serialiser (flat key=value + [section] tables)
// ---------------------------------------------------------------------------

function toToml(obj: Record<string, unknown>, prefix = ""): string {
  const lines: string[] = []
  const tables: [string, Record<string, unknown>][] = []

  for (const [key, value] of Object.entries(obj)) {
    if (value === undefined || value === null) continue
    if (typeof value === "object" && !Array.isArray(value)) {
      tables.push([prefix ? `${prefix}.${key}` : key, value as Record<string, unknown>])
    } else {
      lines.push(`${key} = ${toTomlValue(value)}`)
    }
  }

  let result = lines.join("\n")
  for (const [section, content] of tables) {
    const sectionLines = toToml(content, section)
    if (sectionLines.trim()) {
      result += `\n\n[${section}]\n${sectionLines}`
    }
  }
  return result
}

function toTomlValue(v: unknown): string {
  if (typeof v === "string") return `"${v.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`
  if (typeof v === "boolean") return v ? "true" : "false"
  if (typeof v === "number") return String(v)
  if (Array.isArray(v)) return `[${v.map(toTomlValue).join(", ")}]`
  return `"${String(v)}"`
}

// ---------------------------------------------------------------------------
// Write
// ---------------------------------------------------------------------------

const CODEX_CONFIG_DIR = join(homedir(), ".codex")
const CODEX_CONFIG_PATH = join(CODEX_CONFIG_DIR, "config.toml")

/**
 * Write a Codex config object to `~/.codex/config.toml`.
 * Creates the directory if it doesn't exist.
 */
export async function writeCodexConfig(config: CodexConfig): Promise<string> {
  await mkdir(CODEX_CONFIG_DIR, { recursive: true })
  const header = "# Auto-generated by LegnaCode — Codex compatibility export\n\n"
  const content = header + toToml(config as unknown as Record<string, unknown>)
  await writeFile(CODEX_CONFIG_PATH, content, "utf-8")
  logForDebugging(`[codex-compat] Wrote Codex config to ${CODEX_CONFIG_PATH}`)
  return CODEX_CONFIG_PATH
}
