/**
 * Inline the webui build output into a TypeScript module.
 *
 * Reads webui/dist/ and generates src/server/admin-ui-html.ts
 * containing the HTML, CSS, and JS as separate exported strings.
 *
 * Usage: bun run scripts/inline-webui.ts
 */
import { readFileSync, readdirSync, writeFileSync } from 'fs'
import { resolve, join } from 'path'

const ROOT = resolve(import.meta.dir, '..')
const distDir = resolve(ROOT, 'webui/dist')
const assetsDir = join(distDir, 'assets')

const indexHtml = readFileSync(join(distDir, 'index.html'), 'utf-8')
const assets = readdirSync(assetsDir)
const jsFile = assets.find(f => f.endsWith('.js'))!
const cssFile = assets.find(f => f.endsWith('.css'))!
const jsContent = readFileSync(join(assetsDir, jsFile), 'utf-8')
const cssContent = readFileSync(join(assetsDir, cssFile), 'utf-8')

// Build HTML that references /__admin__/app.js and /__admin__/app.css
let html = indexHtml
  .replace(/<script[^>]*src="[^"]*"[^>]*><\/script>/, '')
  .replace(/<link[^>]*href="[^"]*\.css"[^>]*>/, '<link rel="stylesheet" href="/__admin__/app.css">')
  .replace('</body>', '<script type="module" src="/__admin__/app.js"></script></body>')

const out = [
  '// Auto-generated by scripts/inline-webui.ts — do not edit manually',
  `export const ADMIN_HTML = ${JSON.stringify(html)}`,
  `export const ADMIN_JS = ${JSON.stringify(jsContent)}`,
  `export const ADMIN_CSS = ${JSON.stringify(cssContent)}`,
  '',
].join('\n')
const outPath = resolve(ROOT, 'src/server/admin-ui-html.ts')
writeFileSync(outPath, out)
console.log(`Inlined webui → ${outPath} (${(out.length / 1024).toFixed(1)} KB)`)
